config/routes.rb
Rails.application.routes.draw do
  root 'posts#index', as: 'home'

  get 'about' => 'pages#about', as: 'about'

  resources :posts
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence:true, length: {minimum: 5}
end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
    @title = 'About Us'
    @content = 'this is about page'
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  http_basic_authenticate_with name: "flex", password: "skooma", except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def show
    @post = Post.find(params[:id])
  end

  def create
    # render plain: params[:post].inspect
    @post = Post.new(post_params)

    if(@post.save)
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])

    if(@post.update(post_params))
      redirect_to @post
    else
      render 'edit'
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  private def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Railsapp</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <nav class="navbar navbar-expand-md navbar-dark bg-dark ">
    <%= link_to "Simpleblog", home_path %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="navbar-text">
          <%= link_to "Home", home_path %>
        </li><br>
        <li class="navbar-text">
          <%= link_to "Create Post", new_post_path %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Dropdown</a>
          <div class="dropdown-menu" aria-labelledby="dropdown01">
            <a class="dropdown-item" href="#">Action</a>
            <a class="dropdown-item" href="#">Another action</a>
            <a class="dropdown-item" href="#">Something else here</a>
          </div>
        </li>
      </ul>
    </div>
  </nav>

  <% if signed_in? %>
  Signed in as: <%= current_user.email %>
  <%= button_to 'Sign out', sign_out_path, method: :delete %>
  <% else %>
  <%= link_to 'Sign in', sign_in_path %>
  <% end %>

  <div id="flash">
    <% flash.each do |key, value| %>
    <div class="flash <%= key %>"><%= value %></div>
    <% end %>
  </div>


  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/about.html.erb
<h1><%= @title %></h1>
<p><%= @content %></p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for :post, url: post_path(@post), method: :patch do |f| %>
  <% if @post.errors.any? %>
    <% @post.errors.full_messages.each do |msg| %>
      <div class='alert alert-danger'><%= msg %></div>
    <% end %>
  <% end %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field(:title, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area(:body, {:class => 'form-control'}) %>
  </p>

  <p>
    <%= f.submit({:class => 'btn btn-primary'}) %>
  </p>
<% end %>

app/views/posts/index.html.erb
<h1>Blog Posts</h1>
<% @posts.each do |post| %>
  <div class="well">
    <h3><%= post.title %></h3>
    <p><%= post.body %></p>
    <%= link_to "Read More", post_path(post), :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/posts/new.html.erb
<h1>Add Post</h1>
<%= form_for :post, url: posts_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit :Submit %>
  </p>
<% end %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<p><%= @post.body %></p>
<hr>
<%= link_to "Edit", edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"}, :class => 'btn btn-danger' %>